
version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
