apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp-devops-app
  labels:
    app: mp-devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mp-devops-app
  template:
    metadata:
      labels:
        app: mp-devops-app
    spec:
      containers:
        - name: mp-devops-app
          image: heniinsat/mp-devops:7bb5568
          ports:
            - containerPort: 3000
