apiVersion: v1
kind: Service
metadata:
  name: mp-devops-app-service
  labels:
    app: mp-devops-app
spec:
  type: NodePort
  selector:
    app: mp-devops-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
